name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crDroid Kernel Repository
        uses: actions/checkout@v3
        with:
          repository: crdroidandroid/android_kernel_oplus_RMX3461
          path: android_kernel_oplus_RMX3461

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution here

      - name: Build Kernel
        run: |
          cd android_kernel_oplus_RMX3461
          # Add your build commands here
          echo "Building the kernel..."
          make -j$(nproc)  # Adjust this based on your build process

      - name: Upload Kernel and Module
        uses: actions/upload-artifact@v4
        with:
          name: kernel-module
          path: |
            android_kernel_oplus_RMX3461/arch/arm64/boot/Image.gz  # Adjust based on the output file
            android_kernel_oplus_RMX3461/out/drivers/memkernel/memkernel.ko  # Adjust based on your module path

