name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Build your kernel here
      run: ./user/test.sh  # Adjust the path if the script is in a different folder

    - name: Upload kernel build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: ./path_to_build_output # Adjust this path to where your build outputs are stored
