name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crDroid Kernel Repository
        uses: actions/checkout@v3
        with:
          repository: crdroidandroid/android_kernel_oplus_RMX3461
          path: android_kernel_oplus_RMX3461

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution here

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install adb  # Install adb if needed

      - name: Run Build Script
        run: |
          cd android_kernel_oplus_RMX3461
          chmod +x test.sh
          ./test.sh

      - name: Upload Compiled Kernel
        uses: actions/upload-artifact@v2
        with:
          name: compiled-kernel
          path: android_kernel_oplus_RMX3461/main  # Adjust the path if needed
