name: Build Kernel Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-$(uname -r)

      - name: Compile kernel module
        run: |
          make -C /lib/modules/$(uname -r)/build M=$(pwd) modules

      - name: Upload Module
        uses: actions/upload-artifact@v3  # Ensure you are using the latest version
        with:
          name: kernel-module
          path: your_module.ko  # Change to your compiled module's name
